server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  mvc:
    favicon:
      enabled: false
  application:
    name: product_service
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/product_db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update