## <-- Server config -->
server:
  port: 8080

## <-- Spring config -->
spring:
  output:
    ansi:
      enabled: always
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296
    fail-fast: true
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/product_db
    username: root
    password: ${DB_PASSWORD:hi,welcome}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


## <-- Eureka config -->
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
