## <-- Server config -->
server:
  port: 9296

## <-- Spring config -->
spring:
  output:
    ansi:
      enabled: always
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/joshuaFrias95/spring-app-microservice-config
          clone-on-start: true


## <-- Eureka config -->
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
