## <-- Server config -->
server:
  port: 8082

## <-- Spring config -->
spring:
  output:
    ansi:
      enabled: always
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/order_db
    username: root
    password: ${DB_PASSWORD:hi,welcome}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

## <-- Eureka config -->
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/